config/routes.rb
Qdeploy::Application.routes.draw do

  resources :users

  get "users/index"
  get "users/show"
  get "users/new"
  get "users/edit"
  get "users/create"
  get "users/update"
  get "users/destroy"
  resources :admins

  get '/deployments/get_status', to: 'deployments#get_status'
  get '/deployments/status', as: 'status'
  get '/deployments/get_status', to: 'deployments#get_status', as: 'get_status'
  post '/deployments/get_status', to: 'deployments#get_status', as: 'get_status2'
  post '/deployments/multi', to: 'deployments#multi', as: 'multi'
  post '/deployments/new', to: 'deployments#new'

  get '/deployments/dbrefresh', as: 'dbrefresh'
  post '/deployments/dbrefresh', to: 'deployments#run_dbrefresh', as: 'run_dbrefresh'

  get '/deployments/soarefresh', as: 'soarefresh'
  post '/deployments/soarefresh', to: 'deployments#run_soarefresh', as: 'run_soarefresh'

  get '/deployments/bulkrefresh', as: 'bulkrefresh'
  post '/deployments/bulkrefresh', to: 'deployments#run_bulkrefresh', as: 'run_bulkrefresh'

  get '/deployments/get_refresh', as: 'getrefresh'
  post '/deployments/get_refresh', to: 'deployments#get_refresh', as: 'get_refresh'

  get '/deployments/deploy_stats', as: 'deploy_stats'
  post '/deployments/deploy_stats', to: 'deployments#get_deploy_stats', as: 'get_deploy_stats'

  get '/deployments/project_env_status', as: 'project_env_status'
  get '/deployments/get_project_env_status', to: 'deployments#get_project_env_status', as: 'get_project_env_status'
  post '/deployments/get_project_env_status', to: 'deployments#get_project_env_status', as: 'get_project_env_status2'
  resources :project_to_environments

  resources :incidents

  get 'timeline(.:format)' => 'timeline#index'
  resources :artifacts, only: [:create]

  resources :environments

  resources :tokens

  resources :tokens do
    get :display, on: :collection
  end

  #match 'stats' => 'deployments#stats', :as => 'stats'
  #get 'deployments#stats'
  resources :deployments, only: [:new, :create, :show, :multi] do
    get :tokens, on: :member
    get :logs, on: :member
    get :log, on: :member
    post :new
    post :multi
  end



  resources :projects do
    resources :deployments, :only => [:index, :show]
    resources :tokens
    resources :environments, :only => [:index, :show]
    resources :services do
      post :add_environment, :on => :member
      delete :remove_environment, :on => :member
      resources :environments do
        post :deploy, :on => :member
      end
    end
  end
  get "dashboard/home"
  root to: "projects#index"

end

app/models/service.rb
class Service < ActiveRecord::Base
  include PublicActivity::Model
  belongs_to :project
  
  has_many :tokens, :as => :tokenable, dependent: :destroy
  has_many :service_to_environments, dependent: :destroy
  has_many :environments, :through => :service_to_environments
  
  has_many :artifacts, dependent: :destroy
  

  validates :code, presence: true, uniqueness:  { message: "Service code already in use!"}
  validates :name, presence: true

  def lock_file(env)
    File.join(Rails.configuration.qdeploy.path_prefix, project.code, 'qdeploy', 'tmp', "#{self.code}.#{env}.lock" )
  end
  
  def locked?(env)
    File.exists?(lock_file(env))
  end
  
  def service_path
    File.join(project.project_path, code)
  end
  
  def deployment_logs_path
    File.join(service_path, 'var')
  end
  
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_project
  before_action :set_service, only: [:show, :edit, :update, :destroy, :add_environment, :remove_environment]

  # GET /services
  def index
    @services = @project.services
  end

  # GET /services/1
  def show
  end

  # GET /services/new
  def new
    @service = @project.services.build
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  def create
    @service = @project.services.build(service_params)

    respond_to do |format|
      if @service.save
        @service.create_activity key: 'service.create', owner: current_user
        format.html{redirect_to project_service_path(@project, @service), notice: 'Service was successfully created.'}
        format.js
      else
        format.html{render action: 'new'}
        format.js
      end
    end
  end

  # PATCH/PUT /services/1
  def update
    if @service.update(service_params)
      @service.create_activity key: 'service.update', owner: current_user
      redirect_to project_service_path(@project,@service), notice: 'Service was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /services/1
  def destroy
    @service.destroy
    redirect_to project_services_url(@project)
  end

  def add_environment
    @environment = Environment.find(params[:environment_id])
    @service.environments << @environment
  end

  def remove_environment
    @environment = Environment.find(params[:environment_id])
    ServiceToEnvironment.find_by(environment_id: @environment.id, service_id: @service.id).destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = @project.services.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :code, :description, :project_id)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_environments.haml
#environments
  .well.well-small
    = form_tag add_environment_project_service_path(@project, @service), class: "form-inline", remote: true do 
      = label_tag "Environment"
      = select_tag( :environment_id,
      options_from_collection_for_select(Environment.where.not(:id => @service.environment_ids).sort{|a,b| a.name <=> b.name}, :id, :name),
       class: 'input-small',  disabled: Environment.where.not(:id => @service.environment_ids).empty? ? true : false)
      = button_tag class: "btn btn-success", disabled: Environment.where.not(:id => @service.environment_ids).empty? ? true : false do
        %i.icon-plus-sign
        Add
  %table.table.table-hover.table-condensed.table-striped
    %thead
      %th Environment
      %th Remove
    %tbody
      - @service.environments.order(:name).each do |env|
        %tr
          %td
            = env.name

          %td
            = link_to remove_environment_project_service_path(@project, @service, environment_id: env.id), method: :delete, remote: true, class: 'btn btn-small' do 
              %i.icon-trash

app/views/services/_form.html.haml
= simple_form_for([@project, @service], :html => {:class => 'form-horizontal'}) do |f|
  = f.error_notification
  = f.input :name, hint: "Name of your service e.g. Nexus Reloaded"
  = f.input :code, hint: "e.g. nexus_reloaded"
  = f.input :description, as: :text, input_html: { class: "span6" }, hint: "Short description"

  .form-actions
    = f.button :submit, :class => "btn-primary"
    = submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger"

app/views/services/add_environment.js.haml
!= "$('#environments').html('#{ j render 'environments' }');"

app/views/services/create.js.haml
- if @service.valid?
  != "$('#services table').replaceWith('#{j render 'projects/services'}');"
  != "$('#service-modal').modal('toggle');"
- else
  != "$('#service-modal form').replaceWith('#{j render 'form'}');"

app/views/services/edit.html.haml
%h1 Editing service

= render 'form'

= link_to 'Show', project_service_path(@project, @service)
\|
= link_to 'Back', project_services_path(@project)

app/views/services/index.html.haml
= render 'projects/header'
.pull-right
  = link_to new_project_service_path(@project), class: 'btn', id: 'new-service-link' do
    %i.icon-plus-sign
    Service
%h2.muted
  Services
%table.table.table-hover.table-striped
  %tr
    %th Name
    %th Code
    %th Environments
    %th

  - @services.each do |service|
    %tr
      %td
        = link_to service.name, project_service_path(@project, service)
      %td
        %strong= service.code
      %td
        = service.environments.order("name asc").pluck(:name).join(", ")
      %td
        = link_to project_service_path(@project, service),
        data: {toggle: 'tooltip', title: "Add/Delete Environment"},
        class: 'btn btn-small' do
          %i.icon-adjust
          -#%i.plus-minus-image2.jpeg
          -#%i.icon-plus-sign
          -#%i.icon-minus-sign

        = link_to edit_project_service_path(@project, service),
        data: {toggle: 'tooltip', title: "Edit Service"},
        class: 'btn btn-small' do
          %i.icon-edit
        - if @auth
          = link_to project_service_path(@project, service), :method => :delete,
          :data => { toggle: 'tooltip', title: "Delete Service:  #{service.name}", :confirm => 'Are you sure?' },
           class: 'btn btn-small btn-danger' do
            %i.icon-trash

app/views/services/new.html.haml
%h1 New service

= render 'form'

= link_to 'Back', project_services_path(@project)

app/views/services/remove_environment.js.haml
!= "$('#environments').html('#{ j render 'environments' }');"

app/views/services/show.html.haml
.row-fluid
  .page-header
    %h1
      = @service.name
    %dl.dl-horizontal
      %dt Code
      %dd= @service.code
      %dt Description
      %dd= @service.description


.row-fluid
  .span12
    = render 'environments'