config/routes.rb
Qdeploy::Application.routes.draw do

  resources :users

  get "users/index"
  get "users/show"
  get "users/new"
  get "users/edit"
  get "users/create"
  get "users/update"
  get "users/destroy"
  resources :admins

  get '/deployments/get_status', to: 'deployments#get_status'
  get '/deployments/status', as: 'status'
  get '/deployments/get_status', to: 'deployments#get_status', as: 'get_status'
  post '/deployments/get_status', to: 'deployments#get_status', as: 'get_status2'
  post '/deployments/multi', to: 'deployments#multi', as: 'multi'
  post '/deployments/new', to: 'deployments#new'

  get '/deployments/dbrefresh', as: 'dbrefresh'
  post '/deployments/dbrefresh', to: 'deployments#run_dbrefresh', as: 'run_dbrefresh'

  get '/deployments/soarefresh', as: 'soarefresh'
  post '/deployments/soarefresh', to: 'deployments#run_soarefresh', as: 'run_soarefresh'

  get '/deployments/bulkrefresh', as: 'bulkrefresh'
  post '/deployments/bulkrefresh', to: 'deployments#run_bulkrefresh', as: 'run_bulkrefresh'

  get '/deployments/get_refresh', as: 'getrefresh'
  post '/deployments/get_refresh', to: 'deployments#get_refresh', as: 'get_refresh'

  get '/deployments/deploy_stats', as: 'deploy_stats'
  post '/deployments/deploy_stats', to: 'deployments#get_deploy_stats', as: 'get_deploy_stats'

  get '/deployments/project_env_status', as: 'project_env_status'
  get '/deployments/get_project_env_status', to: 'deployments#get_project_env_status', as: 'get_project_env_status'
  post '/deployments/get_project_env_status', to: 'deployments#get_project_env_status', as: 'get_project_env_status2'
  resources :project_to_environments

  resources :incidents

  get 'timeline(.:format)' => 'timeline#index'
  resources :artifacts, only: [:create]

  resources :environments

  resources :tokens

  resources :tokens do
    get :display, on: :collection
  end

  #match 'stats' => 'deployments#stats', :as => 'stats'
  #get 'deployments#stats'
  resources :deployments, only: [:new, :create, :show, :multi] do
    get :tokens, on: :member
    get :logs, on: :member
    get :log, on: :member
    post :new
    post :multi
  end



  resources :projects do
    resources :deployments, :only => [:index, :show]
    resources :tokens
    resources :environments, :only => [:index, :show]
    resources :services do
      post :add_environment, :on => :member
      delete :remove_environment, :on => :member
      resources :environments do
        post :deploy, :on => :member
      end
    end
  end
  get "dashboard/home"
  root to: "projects#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  include PublicActivity::Model
  validates :name,        presence: true, uniqueness: true
  validates :code,        presence: true, uniqueness: true

  has_many :tokens, :as => :tokenable, dependent: :destroy

  has_many :services, dependent: :destroy
  has_many :artifacts, dependent: :destroy
  has_many :deployments, dependent: :destroy
  has_many :environments, :through => :services
  has_many :project_users

  has_many :projects_repositories
  has_many :repositories, :through => :projects_repositories
  
  def project_path
    File.join(Rails.configuration.qdeploy.path_prefix, code, 'qdeploy' )
  end
  
  def services_path
    File.join(project_path, 'services' )
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :add_environment, :remove_environment]

  # GET /projects
  def index
    @projects = Project.all
  end

  # GET /projects/1
  def show
    @tokenable = @project
    @token = @project.tokens.build
    @services = @project.services.to_a
    @service = @project.services.build
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        @project.create_activity key: 'project.create', owner: current_user
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.js
      else
        format.html { render action: 'new' }
        format.js{ render :json => @project.errors }
      end
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      @project.create_activity key: 'project.update', owner: current_user
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url
  end



  def add_environment
    @environment = Environment.find(params[:environment_id])
    @project.environments << @environment
  end

  def remove_environment
    @environment = Environment.find(params[:environment_id])
    ProjectToEnvironment.find_by(environment_id: @environment.id, project_id: @project.id).destroy
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :code, :description, :recipients)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= simple_form_for(@project, :html => {:class => "form-horizontal"}) do |f|
  = f.error_notification

  = f.input :name, input_html: { class: "span6" }, hint: "Name of your Project e.g. Nexus Reloaded"
  = f.input :code, input_html: { class: "span3" }, hint: "e.g. nexus_reloaded"
  = f.input :recipients, input_html: { class: "span4" }, hint: "e.g. release-1@onekingslane.flowdock.com , ..."
  = f.input :description, as: :text, input_html: { class: "span6" }, hint: "Short Description"

  .form-actions
    = f.button :submit, class: "btn-primary"
    = link_to "or cancel and go back", projects_path

app/views/projects/_header.haml
%h1
  = @project.name
  /-
  %small= @project.code
%p
  .muted
    = @project.description
    %br
    %br
    Notification recipients:
    = @project.recipients
= render_navigation context: :project, :renderer => :bootstrap

app/views/projects/_services.haml
%table#services.table.table-hover.table-condensed
  %thead
    %th Service
    %th Environments
  %tbody
    - @project.services.each do |service|
      - next if !service.persisted?
      %tr
        %td= link_to service.name, project_service_path(@project, service)
        %td
          - service.environments.map(&:name).each do |env|
            %span.label.lable-info= env

app/views/projects/_tokens.haml
%table.table.table-striped.table-hover
  %thead
    %th Name
    %th Value
  %tbody
    - @project.tokens.order("name asc").each do |token|
      %tr
        %td= link_to token.name, token_path(token)
        %td= token.value

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
.span12
  .pull-right
    = link_to new_project_path, :class => "btn btn-success" do
      %i.icon-white.icon-plus-sign
      New Project
  %h1 Projects

  %table.table.table-hover.table-striped.table-condensed
    %thead
      %tr
        %th Project
        %th Services
        %th Deployments
    %tbody
      -# @environments.sort{|a,b| a.name <=> b.name}.each do |environment|
      - @projects.sort{|a,b| a.name.downcase <=> b.name.downcase}.each do |project|
        %tr
          %td
            %i.icon-folder-close.text-warning
            = link_to project.name, project, data: {toggle: 'tooltip', title: project.description }
            -#= link_to project.name, project_path(environment)
            -#\-
            %small.muted= project.code
            = link_to edit_project_path(project)  do
              %i.icon-edit
          %td
            %i.icon-cogs
            = project.services.count
            = link_to "Services", project_services_path(project)
          %td
            %i.icon-cloud
            = project.deployments.count
            = link_to "Deployments", project_deployments_path(project)


-#.span12
-#  .page-header
-#    .pull-right
-#      = link_to new_project_path, :class => 'btn' do
-#        %icon.icon-plus-sign.icon-white
-#        New Project
-#    %h1 Projects
-#
-#  %ul#projectList.unstyled
-#    - @projects.sort{|a,b| a.name.downcase <=> b.name.downcase}.each do |project|
-#      %li
-#        -#.pull-right
-#          #deploymentGraph
-#        -#%h3
-#        %i.icon-folder-close.text-warning
-#        = link_to project.name, project, data: {toggle: 'tooltip', title: project.description }
-#        &nbsp
-#        %small.muted= project.code
-#        = link_to edit_project_path(project) do
-#          &nbsp
-#          %i.icon-edit
-#        .pull-right
-#          %ul.inline.muted.details
-#            %li
-#              %small
-#                %i.icon-cogs
-#                = project.services.count
-#                = link_to "Services", project_services_path(project)
-#            %li
-#              %small
-#                %i.icon-cloud
-#                = project.deployments.count
-#                = link_to "Deployments", project_deployments_path(project)
-#            -#%li
-#              %small
-#                %i.icon-globe
-#                = project.environments.count
-#                = link_to "Environments", project_environments_path(project)
-#        .clearfix
-content_for(:script) do
  :javascript
    var graph = new Rickshaw.Graph( {
        element: document.querySelector("#deploymentGraph"), 
        width: 400, 
        height: 40,
        renderer: 'bar',
        series: [{
            color: 'lightblue',
            data: [ 
                { x: 0, y: 40 },
                { x: 1, y: 49 },
                { x: 2, y: 38 },
                { x: 3, y: 30 },
                { x: 4, y: 32 },
                { x: 5, y: 40 },
                { x: 6, y: 49 },
                { x: 7, y: 38 },
                { x: 8, y: 30 },
                { x: 9, y: 32 },
                { x: 10, y: 40 },
                { x: 11, y: 49 },
                { x: 12, y: 38 },
                { x: 13, y: 30 },
                { x: 14, y: 32 } ]
        }]
    });
    graph.render();

app/views/projects/new.html.haml
.span12
  %h1 New project
  = render 'form'
  = link_to 'Back', projects_path

app/views/projects/show.html.haml
= render 'header'

.row-fluid
  .span12