config/routes.rb
Qdeploy::Application.routes.draw do

  resources :users

  get "users/index"
  get "users/show"
  get "users/new"
  get "users/edit"
  get "users/create"
  get "users/update"
  get "users/destroy"
  resources :admins

  get '/deployments/get_status', to: 'deployments#get_status'
  get '/deployments/status', as: 'status'
  get '/deployments/get_status', to: 'deployments#get_status', as: 'get_status'
  post '/deployments/get_status', to: 'deployments#get_status', as: 'get_status2'
  post '/deployments/multi', to: 'deployments#multi', as: 'multi'
  post '/deployments/new', to: 'deployments#new'

  get '/deployments/dbrefresh', as: 'dbrefresh'
  post '/deployments/dbrefresh', to: 'deployments#run_dbrefresh', as: 'run_dbrefresh'

  get '/deployments/soarefresh', as: 'soarefresh'
  post '/deployments/soarefresh', to: 'deployments#run_soarefresh', as: 'run_soarefresh'

  get '/deployments/bulkrefresh', as: 'bulkrefresh'
  post '/deployments/bulkrefresh', to: 'deployments#run_bulkrefresh', as: 'run_bulkrefresh'

  get '/deployments/get_refresh', as: 'getrefresh'
  post '/deployments/get_refresh', to: 'deployments#get_refresh', as: 'get_refresh'

  get '/deployments/deploy_stats', as: 'deploy_stats'
  post '/deployments/deploy_stats', to: 'deployments#get_deploy_stats', as: 'get_deploy_stats'

  get '/deployments/project_env_status', as: 'project_env_status'
  get '/deployments/get_project_env_status', to: 'deployments#get_project_env_status', as: 'get_project_env_status'
  post '/deployments/get_project_env_status', to: 'deployments#get_project_env_status', as: 'get_project_env_status2'
  resources :project_to_environments

  resources :incidents

  get 'timeline(.:format)' => 'timeline#index'
  resources :artifacts, only: [:create]

  resources :environments

  resources :tokens

  resources :tokens do
    get :display, on: :collection
  end

  #match 'stats' => 'deployments#stats', :as => 'stats'
  #get 'deployments#stats'
  resources :deployments, only: [:new, :create, :show, :multi] do
    get :tokens, on: :member
    get :logs, on: :member
    get :log, on: :member
    post :new
    post :multi
  end



  resources :projects do
    resources :deployments, :only => [:index, :show]
    resources :tokens
    resources :environments, :only => [:index, :show]
    resources :services do
      post :add_environment, :on => :member
      delete :remove_environment, :on => :member
      resources :environments do
        post :deploy, :on => :member
      end
    end
  end
  get "dashboard/home"
  root to: "projects#index"

end

app/models/environment.rb
class Environment < ActiveRecord::Base
  has_many :tokens, :as => :tokenable, dependent: :destroy
  
  
  validates_presence_of :name
  validates_uniqueness_of :name, :code, case_sensitive: false
  validates :env_id, presence: true, numericality: {within: 1..99}
end

app/controllers/environments_controller.rb
class EnvironmentsController < ApplicationController
  before_action :set_environment, only: [:show, :edit, :update, :destroy]

  # GET /environments
  def index
    @environments = Environment.all
  end

  # GET /environments/1
  def show
  end

  # GET /environments/new
  def new
    @environment = Environment.new
  end

  # GET /environments/1/edit
  def edit
  end

  # POST /environments
  def create
    @environment = Environment.new(environment_params)

    if @environment.save
      redirect_to environments_path, notice: 'Environment was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /environments/1
  def update
    if @environment.update(environment_params)
      redirect_to @environment, notice: 'Environment was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /environments/1
  def destroy
    @environment.destroy
    redirect_to environments_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_environment
      @environment = Environment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def environment_params
      params.require(:environment).permit(:name, :code, :env_id)
    end
end

app/helpers/environments_helper.rb
module EnvironmentsHelper
end

app/views/environments/_form.html.haml
= simple_form_for(@environment, :html => {:class => "form-horizontal"}) do |f|
  = f.error_notification

  = f.input :name
  = f.input :code
  = f.input :env_id
  .form-actions
    = f.button :submit, :class => "btn-primary"
    = link_to "or cancel and go back", environments_path

app/views/environments/edit.html.haml
%h1 Editing environment

= render 'form'

= link_to 'Show', @environment
\|
= link_to 'Back', environments_path

app/views/environments/index.html.haml
.span12
  .pull-right
    = link_to new_environment_path, :class => "btn btn-success" do
      %i.icon-white.icon-plus-sign
      Environment
  %h1 Environments

  %table.table.table-hover.table-striped.table-condensed
    %thead
      %tr
        %th Name
        %th Env Prefix#
        %th Edit
        %th Delete
    %tbody
      - @environments.sort{|a,b| a.name <=> b.name}.each do |environment|
        %tr
          %td
            = link_to environment.name, environment_path(environment)
            \-
            %strong= environment.code
          %td
            = environment.env_id
          %td
            = link_to edit_environment_path(environment) do
              %i.icon-edit
          %td
            - if @auth
              = link_to environment, :method => :delete, :data => { :confirm => 'Are you sure?' } do
                %i.icon-trash
    

app/views/environments/new.html.haml
%h1 New environment
= render 'form'

app/views/environments/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @environment.name
%p
  %b Code:
  = @environment.code

= link_to 'Edit', edit_environment_path(@environment)
\|
= link_to 'Back', environments_path